name: TheEducation
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1682637829799205
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1aaa0'
    - '#fefefe'
    - '#1a1b1d'
    - '#3d4749'
    - '#83827d'
  brandStrength: 0.6875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.30889743263833225
purpose: []
